#### Check GPU

In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.constant(1, shape=[5, 5, 10])
y = tf.constant(2, shape=[5, 5, 10])
z = x + y

print(z.eval())

[[[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]

 [[3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]
  [3 3 3 3 3 3 3 3 3 3]]]
